language: ruby

rvm:
  - 2.1.7
  - 2.2.3
  - 2.3.0

gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile

script: bundle exec rake spec

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database "switchman_test";' -U postgres
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - bundle exec rake db:migrate

sudo: false
